version: '3.8'
services:
  user-service:
    build: .
    image: dheepss/user-service-go:1.0
    ports:
      - "8080:8080"
    environment:
      - DB_PATH=./data/userdb.db
    volumes:
      - ./data:/app/data
    networks:
      - app-network
    restart: always

  product-service:
    build: .
    image: dheepss/product-service-go:1.0
    ports:
      - "8081:8081"
    environment:
      - DB_PATH=./data/productdb.db
    volumes:
      - ./data:/app/data
    networks:
      - app-network
    restart: always

networks:
  app-network:
