version: '3.8'
services:
  user-service:
    build: ./user-service
    ports:
      - "8080:8080"
    environment:
      - DB_PATH=./data/userdb.db
    volumes:
      - ./data:/app/data
    networks:
      - app-network
    restart: always

  product-service:
    build: ./product-service
    ports:
      - "8081:8081"
    environment:
      - DB_PATH=./data/productdb.db
    volumes:
      - ./data:/app/data
    networks:
      - app-network
    restart: always

networks:
  app-network:
